name: datecinity
description: DateCinity Dating App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
version: 1.0.3+5

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  # Firebase dependencies
  firebase_core: 3.15.1
  firebase_auth: 5.6.2
  cloud_firestore: 5.6.11
  firebase_messaging: 15.2.9
  flutter_local_notifications: 17.2.4
  firebase_storage: 12.4.9
  cloud_functions: 5.6.1
  google_mobile_ads: 6.0.0

  # Other dependencies
  in_app_purchase: 3.2.3
  flutter_svg: 2.2.0
  country_code_picker: 3.3.0
  scoped_model: 2.0.0
  image_picker: 1.1.2
  image_cropper: 9.1.0
  url_launcher: 6.3.2
  geolocator: 14.0.2
  geocoding: 4.0.0
  rxdart: 0.28.0
  http: 1.4.0
  shimmer: 3.0.0
  timeago: 3.7.1
  share_plus: 11.0.0
  google_maps_flutter: 2.12.3
  flutter_cupertino_datetime_picker: 3.0.0
  fluttertoast: 8.2.12
  permission_handler: 12.0.1
  youtube_player_iframe: 5.2.2
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  config:
    enable-swift-package-manager: false
    
  assets:
     - assets/images/
     - assets/icons/
     - assets/lang/

# Generate android & ios launcher icon settings
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"

# Generate splash logo settings
flutter_native_splash:
  color: "#7F3BBF"
  color_dark: "#7F3BBF"
  image: "assets/images/logo-no-bg.png"
  android: true
  ios: true
  android_12:
    color: "#7F3BBF"
    color_dark: "#7F3BBF"
    image: "assets/images/logo-no-bg.png"
